-- ==========================================
-- Migración 003: Datos Sociodemográficos y Horarios
-- ==========================================

ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS company_id VARCHAR(100) DEFAULT 'emp_kasino';
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS education_level VARCHAR(100);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS is_currently_studying BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS current_study_field VARCHAR(255);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS institution_name VARCHAR(255);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS profession_title VARCHAR(255);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS current_address TEXT;
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS gender VARCHAR(50);
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS training_interest_areas TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS participants ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS company_id VARCHAR(100) DEFAULT 'emp_kasino';
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS education_level VARCHAR(100);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS is_currently_studying BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS current_study_field VARCHAR(255);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS institution_name VARCHAR(255);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS profession_title VARCHAR(255);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS current_address TEXT;
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS gender VARCHAR(50);
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS training_interest_areas TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS users_simulated ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS start_time VARCHAR(50);
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS end_time VARCHAR(50);
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS company_ids TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS total_hours NUMERIC(5,1) DEFAULT 0;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS session_type VARCHAR(100) DEFAULT 'Sincrónica';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS training_type VARCHAR(100) DEFAULT 'Técnico';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS training_format VARCHAR(100) DEFAULT 'Taller';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS program_category VARCHAR(150) DEFAULT 'Capacitacion_seguridad_salud_en_el_trabajo_y_sustentabilidad';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS subprogram VARCHAR(150) DEFAULT 'Sustentabilidad';
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS supplier VARCHAR(255) DEFAULT 'Claro';

ALTER TABLE IF EXISTS event_schedules ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE IF EXISTS event_slots ADD COLUMN IF NOT EXISTS end_time VARCHAR(50);
ALTER TABLE IF EXISTS event_slots ADD COLUMN IF NOT EXISTS checkin_code VARCHAR(50);
ALTER TABLE IF EXISTS event_slots ADD COLUMN IF NOT EXISTS checkout_code VARCHAR(50);
